### ISSUE TITLE
a border does not resize when view resizes

### ISSUE THREAD

**Issue by evgeniyd** [aaronn/UIView-Borders#10]
NOTE: Other folks have already opened issues similar to this, please mark as duplicated if this one has same root.

I have used  UIView-Borders extension with UILabel. When the label does not have text it resizes to `{0,0}` size, but border has frames assigned to it at the point of creation.

![screen-shot-2015-07-07-at-16 32 56](https://cloud.githubusercontent.com/assets/5212518/8547364/0442e6be-24c7-11e5-937d-ebcdeee66ac5.png)

_WORKAROUND:_

```
self.theLabel.clipsToBounds = YES;
```

_UPD: 07/09/2015_

Now, with support from [KVOController](https://github.com/facebook/KVOController) I have updated the workaround. It detects  `UILabel`'s `text` property change, so the clipping is ON, when there is no text (e.g. `{0,0}` size).

```
[self.KVOController observe:_theLabel keyPath:@"text" options:NSKeyValueObservingOptionNew|NSKeyValueObservingOptionOld block:^(MyCell* cell, UILabel *label, NSDictionary *change) {
        NSString* labelText = change[NSKeyValueChangeNewKey];
        if ([labelText isEqual:[NSNull null]] || [labelText isBlank]) {
            label.clipsToBounds = YES;
        }
    }];
```

**Comment by evgeniyd** [comment]
added possible workaround

**Comment by evgeniyd** [comment]
updated workaround

**Comment by aaronn** [comment]
See https://github.com/aaronn/UIView-Borders/pull/11
